server:
  port: 8090
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:postgresql://localhost:5432/ticketbooking?serverTimezone=UTC
    username: postgres
    password: Springter2003
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
api:
  prefix: api/v1
jwt:
  expiration: 2592000
  secretKey: TaqlmGv1iEEDMRiFp/pHuID1+T84IABfuA0xXh4hiUI=